# Generated by Django 4.1.3 on 2022-11-04 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, verbose_name='Sąskaitos išrašymo data')),
                ('bill_sum', models.FloatField(blank=True, verbose_name='Sąskaitos suma')),
                ('status', models.CharField(blank=True, choices=[('A', 'Apmokėta'), ('N', 'Neapmokėta')], default='N', help_text='Užduoties vydymo būklė', max_length=1, verbose_name='Užduoties būklė')),
            ],
            options={
                'verbose_name': 'Sąskaita',
                'verbose_name_plural': 'Sąskaitos',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Įveskite kliento vardą', max_length=50, verbose_name='Vardas')),
                ('last_name', models.CharField(help_text='Įveskite kliento pavardę', max_length=50, verbose_name='Pavardė')),
                ('company', models.CharField(help_text='Įmonės pavadinimas', max_length=50, verbose_name='Įmonė')),
                ('email_field', models.EmailField(help_text='Įveskite kliento elektroninį paštą', max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Įveskite darbuotojo vardą', max_length=100, verbose_name='Vardas')),
                ('last_name', models.CharField(help_text='Įveskite darbuotojo pavardę', max_length=100, verbose_name='Pavardė')),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(help_text='Įveskite darbuotojo pareigas', max_length=100, verbose_name='Pareigos')),
            ],
            options={
                'verbose_name': 'Pareigos',
                'verbose_name_plural': 'Pareigos',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Įveskite darbo pobudį', max_length=100, verbose_name='Atliekamas darbas')),
                ('task_comment', models.TextField(help_text='Įveskite atliekamo darbo pageidavimus', max_length=300, verbose_name='Pastebėjimai')),
                ('status', models.CharField(blank=True, choices=[('A', 'Atlikta'), ('B', 'Baigta'), ('P', 'Pradėta')], default='P', help_text='Užduoties atlikimo būklė', max_length=1, verbose_name='Užduoties būklė')),
            ],
            options={
                'verbose_name': 'Užduotis',
                'verbose_name_plural': 'Užduotys',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite projekto pavadinimą', max_length=200, verbose_name='name')),
                ('date_start', models.DateField(blank=True, verbose_name='Pradžios data')),
                ('date_end', models.DateField(blank=True, verbose_name='Pabaigos data')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images', verbose_name='Nuotrauka')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Aprašymas')),
                ('bills', models.ManyToManyField(help_text='Sąskaitos', to='main.bill', verbose_name='Sąskaitos')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client', verbose_name='Klientas')),
                ('employees', models.ManyToManyField(help_text='Darbuotojai', to='main.employee', verbose_name='Darbuotojai')),
                ('in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Projekto Vadovas')),
                ('tasks', models.ManyToManyField(help_text='Darbai', to='main.task', verbose_name='Užduotys')),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position', verbose_name='Pareigos'),
        ),
    ]
